services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - saifurspublications-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - saifurspublications_postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  app:
    build: .
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    env_file: .env
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - saifurspublications-network
    command: >
      sh -c "mkdir -p public/uploads && 
             chmod -R 775 public/uploads && 
             pnpx prisma migrate deploy && 
             pnpm start"

networks:
  saifurspublications-network:
volumes:
  saifurspublications_postgres_data:
